CREATE TABLE EMP_TEMP2 AS SELECT * FROM EMP;

SELECT * FROM EMP_TEMP2;

--JOB이 MANAGER인 데이터 삭제하기
DELETE FROM EMP_TEMP2 WHERE JOB='MANAGER';

-- 급여 등급이 3등급 사이에 있는 30번 부서의 사원들만 삭제
DELETE FROM EMP_TEMP2 WHERE EMPNO IN (SELECT E.EMPNO
FROM EMP_TEMP2 E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL AND S.GRADE=3 AND DEPTNO=30);

-- DELETE FROM EMP_TEMP2 WHERE EMPNO IN (7000,

--PPT1

CREATE TABLE EXAM_EMP AS SELECT * FROM EMP;

UPDATE EXAM_EMP SET DEPTPNO = 70
WHERE SAL > (SELECT AVG(SAL) FROM EXAM_EMP WHERE DEPTNO=50);

UPDATE EXAM_EMP SET SAL = SAL *1.1, DEPTPNO = 80
WHERE HIREDATE > (SELECT MIN(HIREDATE) FROM EXAM_EMP WHERE DEPTNO=60);

DELETE FROM EXAM_EMP WHERE EMPNO IN (SELECT EMPNO
FROM EXAM_EMP, SALGRADE WHERE SAL BETWEEN LASAL AND HISAL AND GRADE=5);